# Copyright (c) 2017-present SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    component: velero
  name: node-agent
  namespace: kube-system
spec:
  selector:
    matchLabels:
      k8s-app: velero-node-agent
      name: node-agent
      component: velero
  template:
    metadata:
      labels:
        k8s-app: velero-node-agent
        name: node-agent
        component: velero
    spec:
      securityContext:
        runAsUser: 0
      containers:
      - args:
        - node-agent
        - server
        - --features=
        command:
        - /velero
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: VELERO_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: VELERO_SCRATCH_DIR
          value: /scratch
        - name: AZURE_CREDENTIALS_FILE
          value: /credentials/cloud
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /credentials/cloud
        - name: AWS_SHARED_CREDENTIALS_FILE
          value: /credentials/cloud
        image: velero/velero
        imagePullPolicy: Always
        ports:
        - containerPort: 8085
          name: metrics
        securityContext:
          privileged: false
          allowPrivilegeEscalation: false
        name: node-agent
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - mountPath: /host_pods
          mountPropagation: HostToContainer
          name: host-pods
        - mountPath: /var/lib/kubelet/plugins
          mountPropagation: HostToContainer
          name: host-plugins
        - mountPath: /scratch
          name: scratch
        - mountPath: /credentials
          name: cloud-credentials
      serviceAccountName: velero
      volumes:
      - hostPath:
          path: /var/lib/kubelet/pods
        name: host-pods
      - hostPath:
          path: /var/lib/kubelet/plugins
        name: host-plugins
      - emptyDir: {}
        name: scratch
      - name: cloud-credentials
        secret:
          secretName: cloud-credentials
